SHELL := /bin/bash

.DEFAULT: help
help:
	@echo "make venv"
	@echo "       Make a python virtual enviroment in the cwd and install requirements"

venv:
	pip install virtualenv
	python -m venv venv
	source venv/bin/activate && pip install matatika &&	pip install matatika-iplotter && pip install bios
